//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 04/12/2014 09:13:39 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain.Entities
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Entities.account, Pharma.Domain in the schema.
    /// </summary>
    public partial class account {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for account constructor in the schema.
        /// </summary>
        public account()
        {
            this.account_has_grupos_roles = new HashSet<account_has_grupos_roles>();
            this.sessions = new HashSet<sessions>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Password in the schema.
        /// </summary>
        public virtual string Password
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EncryptKey in the schema.
        /// </summary>
        public virtual byte[] EncryptKey
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EncryptIV in the schema.
        /// </summary>
        public virtual byte[] EncryptIV
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsArchived in the schema.
        /// </summary>
        public virtual bool? IsArchived
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_crea in the schema.
        /// </summary>
        public virtual DateTime? fecha_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_actu in the schema.
        /// </summary>
        public virtual DateTime? fecha_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_crea in the schema.
        /// </summary>
        public virtual string usuario_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_actu in the schema.
        /// </summary>
        public virtual string usuario_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for account_has_grupos_roles in the schema.
        /// </summary>
        public virtual ICollection<account_has_grupos_roles> account_has_grupos_roles
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        public virtual ICollection<sessions> sessions
        {
            get;
            set;
        }
    }

}
