//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 28/11/2014 03:52:58 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain.Entities
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Entities.ajustes, Pharma.Domain in the schema.
    /// </summary>
    public partial class ajustes {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for ajustes constructor in the schema.
        /// </summary>
        public ajustes()
        {
            this.detalle_ajustes = new HashSet<detalle_ajustes>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for id_ajuste in the schema.
        /// </summary>
        public virtual int id_ajuste
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for cant_producto in the schema.
        /// </summary>
        public virtual System.Nullable<int> cant_producto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_crea in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_actu in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_crea in the schema.
        /// </summary>
        public virtual string usuario_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_actu in the schema.
        /// </summary>
        public virtual string usuario_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for id_tipotran in the schema.
        /// </summary>
        public virtual int id_tipotran
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for tipo_transacciones in the schema.
        /// </summary>
        public virtual tipo_transacciones tipo_transacciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for detalle_ajustes in the schema.
        /// </summary>
        public virtual ISet<detalle_ajustes> detalle_ajustes
        {
            get;
            set;
        }
    }

}
