//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 14/11/2014 06:38:23 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Pharma.Domain.Entities
{

    /// <summary>
    /// There are no comments for Pharma.Domain.clientes, Pharma.Domain in the schema.
    /// </summary>
    public partial class clientes {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for clientes constructor in the schema.
        /// </summary>
        public clientes()
        {
            this.contactos_clientes = new HashSet<contactos_clientes>();
            this.direcciones_clientes = new HashSet<direcciones_clientes>();
            this.facturas = new HashSet<facturas>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for id_cliente in the schema.
        /// </summary>
        public virtual int id_cliente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for nombre in the schema.
        /// </summary>
        public virtual string nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_crea in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_actu in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_crea in the schema.
        /// </summary>
        public virtual string usuario_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_actu in the schema.
        /// </summary>
        public virtual string usuario_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for contactos_clientes in the schema.
        /// </summary>
        public virtual ISet<contactos_clientes> contactos_clientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for direcciones_clientes in the schema.
        /// </summary>
        public virtual ISet<direcciones_clientes> direcciones_clientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for facturas in the schema.
        /// </summary>
        public virtual ISet<facturas> facturas
        {
            get;
            set;
        }
    }

}
