//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Customer, Pharma.Domain in the schema.
    /// </summary>
    public partial class Customer {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Customer constructor in the schema.
        /// </summary>
        public Customer()
        {
            this.CustomerName = @"NULL";
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            this.Addresses = new HashSet<Address>();
            this.Customercontacts = new HashSet<CustomerContact>();
            this.Invoices = new HashSet<Invoice>();
            this.Phonenumbers = new HashSet<PhoneNumber>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CustomerId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int CustomerId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CustomerName in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CustomerName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public virtual ISet<Address> Addresses
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customertype in the schema.
        /// </summary>
        public virtual CustomerType Customertype
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customercontacts in the schema.
        /// </summary>
        public virtual ISet<CustomerContact> Customercontacts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        public virtual ISet<Invoice> Invoices
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Phonenumbers in the schema.
        /// </summary>
        public virtual ISet<PhoneNumber> Phonenumbers
        {
            get;
            set;
        }
    }

}
