//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/11/2014 01:41:26 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.detalle_compras, Pharma.Domain in the schema.
    /// </summary>
    public partial class detalle_compras {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          detalle_compras toCompare = obj as detalle_compras;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.num_detalle, toCompare.num_detalle))
            return false;
          if (!Object.Equals(this.id_compra, toCompare.id_compra))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + num_detalle.GetHashCode();
          hashCode = (hashCode * 7) + id_compra.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for detalle_compras constructor in the schema.
        /// </summary>
        public detalle_compras()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for num_detalle in the schema.
        /// </summary>
        public virtual int num_detalle
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for id_compra in the schema.
        /// </summary>
        public virtual int id_compra
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for cantidad in the schema.
        /// </summary>
        public virtual System.Nullable<int> cantidad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for precio_compra in the schema.
        /// </summary>
        public virtual System.Nullable<double> precio_compra
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for subtotal in the schema.
        /// </summary>
        public virtual System.Nullable<double> subtotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for cod_prod in the schema.
        /// </summary>
        public virtual int cod_prod
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for compras in the schema.
        /// </summary>
        public virtual compras compras
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for productos in the schema.
        /// </summary>
        public virtual productos productos
        {
            get;
            set;
        }
    }

}
