//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/11/2014 01:41:26 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.facturas, Pharma.Domain in the schema.
    /// </summary>
    public partial class facturas {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for facturas constructor in the schema.
        /// </summary>
        public facturas()
        {
            this.detallle_facturas = new HashSet<detallle_facturas>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for num_factura in the schema.
        /// </summary>
        public virtual int num_factura
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for subtotal in the schema.
        /// </summary>
        public virtual System.Nullable<double> subtotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for isv in the schema.
        /// </summary>
        public virtual System.Nullable<double> isv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for descuento in the schema.
        /// </summary>
        public virtual System.Nullable<double> descuento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for total in the schema.
        /// </summary>
        public virtual System.Nullable<double> total
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for id_cliente in the schema.
        /// </summary>
        public virtual int id_cliente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for clientes in the schema.
        /// </summary>
        public virtual clientes clientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for detallle_facturas in the schema.
        /// </summary>
        public virtual ISet<detallle_facturas> detallle_facturas
        {
            get;
            set;
        }
    }

}
