//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 03/12/2014 09:55:51 a.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain.Entities
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Entities.facturas, Pharma.Domain in the schema.
    /// </summary>
    public partial class facturas {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for facturas constructor in the schema.
        /// </summary>
        public facturas()
        {
            this.detalle_facturas = new HashSet<detalle_facturas>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for num_factura in the schema.
        /// </summary>
        public virtual int num_factura
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha in the schema.
        /// </summary>
        public virtual DateTime? fecha
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for subtotal in the schema.
        /// </summary>
        public virtual double? subtotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for isv in the schema.
        /// </summary>
        public virtual double? isv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for descuento in the schema.
        /// </summary>
        public virtual double? descuento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for total in the schema.
        /// </summary>
        public virtual double? total
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_crea in the schema.
        /// </summary>
        public virtual DateTime? fecha_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_actu in the schema.
        /// </summary>
        public virtual DateTime? fecha_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_crea in the schema.
        /// </summary>
        public virtual string usuario_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_actu in the schema.
        /// </summary>
        public virtual string usuario_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for id_cliente in the schema.
        /// </summary>
        public virtual int id_cliente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for clientes in the schema.
        /// </summary>
        public virtual clientes clientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for detalle_facturas in the schema.
        /// </summary>
        public virtual ISet<detalle_facturas> detalle_facturas
        {
            get;
            set;
        }
    }

}
