//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.InventoryaAjustmentDetail, Pharma.Domain in the schema.
    /// </summary>
    public partial class InventoryaAjustmentDetail {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          InventoryaAjustmentDetail toCompare = obj as InventoryaAjustmentDetail;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.AdjustmentDetailNumber, toCompare.AdjustmentDetailNumber))
            return false;
          if (!Object.Equals(this.AdjustmentId, toCompare.AdjustmentId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + AdjustmentDetailNumber.GetHashCode();
          hashCode = (hashCode * 7) + AdjustmentId.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for InventoryaAjustmentDetail constructor in the schema.
        /// </summary>
        public InventoryaAjustmentDetail()
        {
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for AdjustmentDetailNumber in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int AdjustmentDetailNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AdjustmentId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int AdjustmentId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Quantity in the schema.
        /// </summary>
        public virtual System.Nullable<int> Quantity
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inventoryadjustment in the schema.
        /// </summary>
        public virtual InventoryAdjustment Inventoryadjustment
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public virtual Product Product
        {
            get;
            set;
        }
    }

}
