//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Invoice, Pharma.Domain in the schema.
    /// </summary>
    public partial class Invoice {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Invoice constructor in the schema.
        /// </summary>
        public Invoice()
        {
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            this.Invoicedetails = new HashSet<InvoiceDetail>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for InvoiceId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int InvoiceId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InvoiceDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> InvoiceDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SubTotal in the schema.
        /// </summary>
        public virtual System.Nullable<float> SubTotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SalesTax in the schema.
        /// </summary>
        public virtual System.Nullable<float> SalesTax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Disccount in the schema.
        /// </summary>
        public virtual System.Nullable<float> Disccount
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        public virtual Customer Customer
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Invoicedetails in the schema.
        /// </summary>
        public virtual ISet<InvoiceDetail> Invoicedetails
        {
            get;
            set;
        }
    }

}
