//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.KardexOperation, Pharma.Domain in the schema.
    /// </summary>
    public partial class KardexOperation {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for KardexOperation constructor in the schema.
        /// </summary>
        public KardexOperation()
        {
            this.OperationName = @"NULL";
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for OperationId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int OperationId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OperationName in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string OperationName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProductCost in the schema.
        /// </summary>
        public virtual System.Nullable<float> ProductCost
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PreviousExistence in the schema.
        /// </summary>
        public virtual System.Nullable<int> PreviousExistence
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NewExistence in the schema.
        /// </summary>
        public virtual System.Nullable<int> NewExistence
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProductPrice in the schema.
        /// </summary>
        public virtual System.Nullable<float> ProductPrice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Quantity in the schema.
        /// </summary>
        public virtual System.Nullable<int> Quantity
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OperationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> OperationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public virtual Product Product
        {
            get;
            set;
        }
    }

}
