//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Product, Pharma.Domain in the schema.
    /// </summary>
    public partial class Product {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Product constructor in the schema.
        /// </summary>
        public Product()
        {
            this.ProductName = @"NULL";
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            this.Estimatedetails = new HashSet<EstimateDetail>();
            this.Inventoryadjustmentdetails = new HashSet<InventoryaAjustmentDetail>();
            this.Invoicedetails = new HashSet<InvoiceDetail>();
            this.Kardexoperations = new HashSet<KardexOperation>();
            this.Providersellsproducts = new HashSet<ProviderSellsProduct>();
            this.Purchasedetails = new HashSet<PurchaseDetail>();
            this.Purchaseorderdetails = new HashSet<PurchaseOrderDetail>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ProductId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int ProductId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProductName in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ProductName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RetailPrice in the schema.
        /// </summary>
        public virtual System.Nullable<float> RetailPrice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cost in the schema.
        /// </summary>
        public virtual System.Nullable<float> Cost
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MinimumExistence in the schema.
        /// </summary>
        public virtual System.Nullable<long> MinimumExistence
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for WholeSalerPercentage in the schema.
        /// </summary>
        public virtual System.Nullable<float> WholeSalerPercentage
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ExpireDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ExpireDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CurrentExistence in the schema.
        /// </summary>
        public virtual System.Nullable<int> CurrentExistence
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public virtual Category Category
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Estimatedetails in the schema.
        /// </summary>
        public virtual ISet<EstimateDetail> Estimatedetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inventoryadjustmentdetails in the schema.
        /// </summary>
        public virtual ISet<InventoryaAjustmentDetail> Inventoryadjustmentdetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Invoicedetails in the schema.
        /// </summary>
        public virtual ISet<InvoiceDetail> Invoicedetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Kardexoperations in the schema.
        /// </summary>
        public virtual ISet<KardexOperation> Kardexoperations
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Presentation in the schema.
        /// </summary>
        public virtual Presentation Presentation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Providersellsproducts in the schema.
        /// </summary>
        public virtual ISet<ProviderSellsProduct> Providersellsproducts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Purchasedetails in the schema.
        /// </summary>
        public virtual ISet<PurchaseDetail> Purchasedetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Purchaseorderdetails in the schema.
        /// </summary>
        public virtual ISet<PurchaseOrderDetail> Purchaseorderdetails
        {
            get;
            set;
        }
    }

}
