//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Provider, Pharma.Domain in the schema.
    /// </summary>
    public partial class Provider {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Provider constructor in the schema.
        /// </summary>
        public Provider()
        {
            this.Name = @"NULL";
            this.Phone = @"NULL";
            this.ContactName = @"NULL";
            this.Address = @"NULL";
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            this.Priceestimates = new HashSet<PriceEstimate>();
            this.Providersellsproducts = new HashSet<ProviderSellsProduct>();
            this.Purchases = new HashSet<Purchase>();
            this.Purchaseorders = new HashSet<PurchaseOrder>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ProviderId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int ProviderId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Phone in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string Phone
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContactName in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ContactName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string Address
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Priceestimates in the schema.
        /// </summary>
        public virtual ISet<PriceEstimate> Priceestimates
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Providersellsproducts in the schema.
        /// </summary>
        public virtual ISet<ProviderSellsProduct> Providersellsproducts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Purchases in the schema.
        /// </summary>
        public virtual ISet<Purchase> Purchases
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Purchaseorders in the schema.
        /// </summary>
        public virtual ISet<PurchaseOrder> Purchaseorders
        {
            get;
            set;
        }
    }

}
