//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.ProviderSellsProduct, Pharma.Domain in the schema.
    /// </summary>
    public partial class ProviderSellsProduct {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          ProviderSellsProduct toCompare = obj as ProviderSellsProduct;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ProviderId, toCompare.ProviderId))
            return false;
          if (!Object.Equals(this.ProductId, toCompare.ProductId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ProviderId.GetHashCode();
          hashCode = (hashCode * 7) + ProductId.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for ProviderSellsProduct constructor in the schema.
        /// </summary>
        public ProviderSellsProduct()
        {
            this.CreatedByUser = @"NULL";
            this.ModifiedByUser = @"NULL";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ProviderId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int ProviderId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProductId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int ProductId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cost in the schema.
        /// </summary>
        public virtual System.Nullable<float> Cost
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string CreatedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedByUser in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public virtual string ModifiedByUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public virtual Product Product
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Provider in the schema.
        /// </summary>
        public virtual Provider Provider
        {
            get;
            set;
        }
    }

}
