//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/11/2014 07:41:46 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.proveedores, Pharma.Domain in the schema.
    /// </summary>
    public partial class proveedores {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for proveedores constructor in the schema.
        /// </summary>
        public proveedores()
        {
            this.compras = new HashSet<compras>();
            this.cotizaciones = new HashSet<cotizaciones>();
            this.ordenes_de_compras = new HashSet<ordenes_de_compra>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for id_proveedor in the schema.
        /// </summary>
        public virtual int id_proveedor
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for direccion in the schema.
        /// </summary>
        public virtual string direccion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for telefono in the schema.
        /// </summary>
        public virtual string telefono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for nombre in the schema.
        /// </summary>
        public virtual string nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for contacto in the schema.
        /// </summary>
        public virtual string contacto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_crea in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_actu in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_crea in the schema.
        /// </summary>
        public virtual string usuario_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_actu in the schema.
        /// </summary>
        public virtual string usuario_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for compras in the schema.
        /// </summary>
        public virtual ISet<compras> compras
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for cotizaciones in the schema.
        /// </summary>
        public virtual ISet<cotizaciones> cotizaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ordenes_de_compras in the schema.
        /// </summary>
        public virtual ISet<ordenes_de_compra> ordenes_de_compras
        {
            get;
            set;
        }
    }

}
