//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/7/2014 11:40:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.PurchaseDetail, Pharma.Domain in the schema.
    /// </summary>
    public partial class PurchaseDetail {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          PurchaseDetail toCompare = obj as PurchaseDetail;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.PurchaseDetailNumber, toCompare.PurchaseDetailNumber))
            return false;
          if (!Object.Equals(this.PurchaseId, toCompare.PurchaseId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + PurchaseDetailNumber.GetHashCode();
          hashCode = (hashCode * 7) + PurchaseId.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for PurchaseDetail constructor in the schema.
        /// </summary>
        public PurchaseDetail()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for PurchaseDetailNumber in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int PurchaseDetailNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PurchaseId in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int PurchaseId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PurchasePrice in the schema.
        /// </summary>
        public virtual System.Nullable<float> PurchasePrice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Quantity in the schema.
        /// </summary>
        public virtual System.Nullable<int> Quantity
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Subtotal in the schema.
        /// </summary>
        public virtual System.Nullable<float> Subtotal
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifyDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public virtual Product Product
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        public virtual Purchase Purchase
        {
            get;
            set;
        }
    }

}
