//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 04/12/2014 09:13:39 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain.Entities
{

    /// <summary>
    /// There are no comments for Pharma.Domain.Entities.sessions, Pharma.Domain in the schema.
    /// </summary>
    public partial class sessions {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for sessions constructor in the schema.
        /// </summary>
        public sessions()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LoginDate in the schema.
        /// </summary>
        public virtual DateTime LoginDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ExpirationTime in the schema.
        /// </summary>
        public virtual DateTime ExpirationTime
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Token in the schema.
        /// </summary>
        public virtual string Token
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsArchived in the schema.
        /// </summary>
        public virtual bool? IsArchived
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for User_id in the schema.
        /// </summary>
        public virtual long? User_id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for account in the schema.
        /// </summary>
        public virtual account account
        {
            get;
            set;
        }
    }

}
