//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/11/2014 01:41:26 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.tipo_transacciones, Pharma.Domain in the schema.
    /// </summary>
    public partial class tipo_transacciones {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for tipo_transacciones constructor in the schema.
        /// </summary>
        public tipo_transacciones()
        {
            this.ajustes = new HashSet<ajustes>();
            this.kardexes = new HashSet<kardex>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for id_tipotran in the schema.
        /// </summary>
        public virtual int id_tipotran
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for nombre in the schema.
        /// </summary>
        public virtual string nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ajustes in the schema.
        /// </summary>
        public virtual ISet<ajustes> ajustes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for kardexes in the schema.
        /// </summary>
        public virtual ISet<kardex> kardexes
        {
            get;
            set;
        }
    }

}
