//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12/11/2014 07:41:46 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Pharma.Domain
{

    /// <summary>
    /// There are no comments for Pharma.Domain.usuarios, Pharma.Domain in the schema.
    /// </summary>
    public partial class usuarios {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for usuarios constructor in the schema.
        /// </summary>
        public usuarios()
        {
            this.grupos_roles = new HashSet<grupos_roles>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for usuario in the schema.
        /// </summary>
        public virtual string usuario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for correo in the schema.
        /// </summary>
        public virtual string correo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for nombre in the schema.
        /// </summary>
        public virtual string nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for clave in the schema.
        /// </summary>
        public virtual System.Nullable<byte> clave
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for key in the schema.
        /// </summary>
        public virtual System.Nullable<byte> key
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_crea in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for fecha_actu in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> fecha_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_crea in the schema.
        /// </summary>
        public virtual string usuario_crea
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for usuario_actu in the schema.
        /// </summary>
        public virtual string usuario_actu
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for grupos_roles in the schema.
        /// </summary>
        public virtual ISet<grupos_roles> grupos_roles
        {
            get;
            set;
        }
    }

}
