-- MySQL Script generated by MySQL Workbench
-- 11/11/14 23:50:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`PRESENTACION_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`PRESENTACION_PRODUCTOS` (
  `cod_presentacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_presentacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`CATEGORIA_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`CATEGORIA_PRODUCTOS` (
  `cod_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`PRODUCTOS` (
  `cod_prod` INT NOT NULL,
  `existencia` INT NULL,
  `fecha_venc` DATE NULL,
  `costo` FLOAT NULL,
  `precio_consumi` FLOAT NULL,
  `precio_mayor` FLOAT NULL,
  `nombre` VARCHAR(45) NULL,
  `cod_presentacion` INT NULL,
  `cod_categoria` INT NULL,
  `existencia_min` INT NULL,
  `existencia_max` INT NULL,
  `porcentaje_m` INT NULL,
  PRIMARY KEY (`cod_prod`),
  INDEX `fk_PRODUCTO_PRESENTACION_PRODUCTO_idx` (`cod_presentacion` ASC),
  INDEX `fk_PRODUCTO_CATEGORIA_PRODUCTO1_idx` (`cod_categoria` ASC),
  CONSTRAINT `fk_PRODUCTO_PRESENTACION_PRODUCTO`
    FOREIGN KEY (`cod_presentacion`)
    REFERENCES `farmacia`.`PRESENTACION_PRODUCTOS` (`cod_presentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA_PRODUCTO1`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `farmacia`.`CATEGORIA_PRODUCTOS` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`CLIENTES` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`FACTURAS` (
  `num_factura` INT NOT NULL,
  `fecha` DATE NULL,
  `subtotal` DOUBLE NULL,
  `isv` DOUBLE NULL,
  `descuento` DOUBLE NULL,
  `total` DOUBLE NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`num_factura`),
  INDEX `fk_FACTURAS_CLIENTES1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_FACTURAS_CLIENTES1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `farmacia`.`CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`DETALLLE_FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`DETALLLE_FACTURAS` (
  `num_detalle` INT NOT NULL,
  `precio_venta` DOUBLE NULL,
  `cantidad` INT NULL,
  `subtotal` DOUBLE NULL,
  `num_factura` INT NOT NULL,
  `cod_prod` INT NOT NULL,
  PRIMARY KEY (`num_detalle`, `num_factura`),
  INDEX `fk_DETALLLE_FACTURAS_FACTURAS1_idx` (`num_factura` ASC),
  INDEX `fk_DETALLLE_FACTURAS_PRODUCTOS1_idx` (`cod_prod` ASC),
  CONSTRAINT `fk_DETALLLE_FACTURAS_FACTURAS1`
    FOREIGN KEY (`num_factura`)
    REFERENCES `farmacia`.`FACTURAS` (`num_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLLE_FACTURAS_PRODUCTOS1`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `farmacia`.`PRODUCTOS` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`DIRECCIONES_CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`DIRECCIONES_CLIENTES` (
  `direccion` VARCHAR(50) NOT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`direccion`, `id_cliente`),
  INDEX `fk_DIRECCIONES_CLIENTES_CLIENTES1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_DIRECCIONES_CLIENTES_CLIENTES1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `farmacia`.`CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`CONTACTOS_CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`CONTACTOS_CLIENTES` (
  `nombre` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`nombre`, `correo`, `telefono`, `id_cliente`),
  INDEX `fk_CONTACTOS_CLIENTES_CLIENTES1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_CONTACTOS_CLIENTES_CLIENTES1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `farmacia`.`CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`PROVEEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`PROVEEDORES` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `nombre` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`COMPRAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`COMPRAS` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `total` DOUBLE NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_COMPRAS_PROVEEDORES1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_COMPRAS_PROVEEDORES1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `farmacia`.`PROVEEDORES` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`DETALLE_COMPRAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`DETALLE_COMPRAS` (
  `num_detalle` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_compra` DOUBLE NULL,
  `subtotal` DOUBLE NULL,
  `id_compra` INT NOT NULL,
  `cod_prod` INT NOT NULL,
  PRIMARY KEY (`num_detalle`, `id_compra`),
  INDEX `fk_DETALLE_COMPRAS_COMPRAS1_idx` (`id_compra` ASC),
  INDEX `fk_DETALLE_COMPRAS_PRODUCTOS1_idx` (`cod_prod` ASC),
  CONSTRAINT `fk_DETALLE_COMPRAS_COMPRAS1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `farmacia`.`COMPRAS` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_COMPRAS_PRODUCTOS1`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `farmacia`.`PRODUCTOS` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`ORDENES_DE_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`ORDENES_DE_COMPRA` (
  `id_ordencompra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `total` DOUBLE NULL,
  `id_proveedor` INT NOT NULL,
  `ejecutada` INT NULL,
  `cancelada` INT NULL,
  `activa` INT NULL,
  PRIMARY KEY (`id_ordencompra`),
  INDEX `fk_ORDENES_DE_COMPRA_PROVEEDORES1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_ORDENES_DE_COMPRA_PROVEEDORES1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `farmacia`.`PROVEEDORES` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`DETALLE_OC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`DETALLE_OC` (
  `num_detalle` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` DOUBLE NULL,
  `precio_unit` DOUBLE NULL,
  `id_ordencompra` INT NOT NULL,
  `cod_prod` INT NOT NULL,
  PRIMARY KEY (`num_detalle`, `id_ordencompra`),
  INDEX `fk_DETALLE_OC_ORDENES_DE_COMPRA1_idx` (`id_ordencompra` ASC),
  INDEX `fk_DETALLE_OC_PRODUCTOS1_idx` (`cod_prod` ASC),
  CONSTRAINT `fk_DETALLE_OC_ORDENES_DE_COMPRA1`
    FOREIGN KEY (`id_ordencompra`)
    REFERENCES `farmacia`.`ORDENES_DE_COMPRA` (`id_ordencompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_OC_PRODUCTOS1`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `farmacia`.`PRODUCTOS` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`COTIZACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`COTIZACIONES` (
  `id_cotizacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `tota` DOUBLE NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_cotizacion`),
  INDEX `fk_COTIZACIONES_PROVEEDORES1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_COTIZACIONES_PROVEEDORES1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `farmacia`.`PROVEEDORES` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`DETALLE_COTIZACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`DETALLE_COTIZACIONES` (
  `num_detalle` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_unit` DOUBLE NULL,
  `cantidad` INT NULL,
  `id_cotizacion` INT NOT NULL,
  `cod_prod` INT NOT NULL,
  PRIMARY KEY (`num_detalle`, `id_cotizacion`),
  INDEX `fk_DETALLE_COTIZACIONES_COTIZACIONES1_idx` (`id_cotizacion` ASC),
  INDEX `fk_DETALLE_COTIZACIONES_PRODUCTOS1_idx` (`cod_prod` ASC),
  CONSTRAINT `fk_DETALLE_COTIZACIONES_COTIZACIONES1`
    FOREIGN KEY (`id_cotizacion`)
    REFERENCES `farmacia`.`COTIZACIONES` (`id_cotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_COTIZACIONES_PRODUCTOS1`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `farmacia`.`PRODUCTOS` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`TIPO_TRANSACCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`TIPO_TRANSACCIONES` (
  `id_tipotran` INT NOT NULL,
  `nombre` VARCHAR(15) NULL,
  PRIMARY KEY (`id_tipotran`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`AJUSTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`AJUSTES` (
  `id_ajuste` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `cant_producto` INT NULL,
  `id_tipotran` INT NOT NULL,
  PRIMARY KEY (`id_ajuste`),
  INDEX `fk_AJUSTES_TIPO_TRANSACCIONES1_idx` (`id_tipotran` ASC),
  CONSTRAINT `fk_AJUSTES_TIPO_TRANSACCIONES1`
    FOREIGN KEY (`id_tipotran`)
    REFERENCES `farmacia`.`TIPO_TRANSACCIONES` (`id_tipotran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`DETALLE_AJUSTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`DETALLE_AJUSTES` (
  `num_detalle` INT NOT NULL,
  `cantidad` INT NULL,
  `id_ajuste` INT NOT NULL,
  `cod_prod` INT NOT NULL,
  PRIMARY KEY (`num_detalle`, `id_ajuste`),
  INDEX `fk_DETALLE_AJUSTES_AJUSTES1_idx` (`id_ajuste` ASC),
  INDEX `fk_DETALLE_AJUSTES_PRODUCTOS1_idx` (`cod_prod` ASC),
  CONSTRAINT `fk_DETALLE_AJUSTES_AJUSTES1`
    FOREIGN KEY (`id_ajuste`)
    REFERENCES `farmacia`.`AJUSTES` (`id_ajuste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_AJUSTES_PRODUCTOS1`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `farmacia`.`PRODUCTOS` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`KARDEX`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`KARDEX` (
  `id_operacion` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `costo` DOUBLE NULL,
  `inv_antes` INT NULL,
  `inv_despues` INT NULL,
  `fecha` DATE NULL,
  `precio` DOUBLE NULL,
  `id_tipotran` INT NOT NULL,
  PRIMARY KEY (`id_operacion`),
  INDEX `fk_KARDEX_TIPO_TRANSACCIONES1_idx` (`id_tipotran` ASC),
  CONSTRAINT `fk_KARDEX_TIPO_TRANSACCIONES1`
    FOREIGN KEY (`id_tipotran`)
    REFERENCES `farmacia`.`TIPO_TRANSACCIONES` (`id_tipotran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`LOG_DE_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`LOG_DE_USUARIOS` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `fecha_crea` DATETIME NULL,
  `fecha_actu` DATETIME NULL,
  `usuario_crea` VARCHAR(45) NULL,
  `usuario_actu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`USUARIOS` (
  `usuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `clave` BINARY NULL,
  `key` BINARY NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`GRUPOS_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`GRUPOS_ROLES` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`PRIVILEGIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`PRIVILEGIOS` (
  `id_privilegio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_privilegio`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `farmacia`.`USUARIOS_has_GRUPOS_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`USUARIOS_has_GRUPOS_ROLES` (
  `usuario` VARCHAR(45) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`usuario`, `id_rol`),
  INDEX `fk_USUARIOS_has_GRUPOS_ROLES_GRUPOS_ROLES1_idx` (`id_rol` ASC),
  INDEX `fk_USUARIOS_has_GRUPOS_ROLES_USUARIOS1_idx` (`usuario` ASC),
  CONSTRAINT `fk_USUARIOS_has_GRUPOS_ROLES_USUARIOS1`
    FOREIGN KEY (`usuario`)
    REFERENCES `farmacia`.`USUARIOS` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_has_GRUPOS_ROLES_GRUPOS_ROLES1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `farmacia`.`GRUPOS_ROLES` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`GRUPOS_ROLES_has_PRIVILEGIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`GRUPOS_ROLES_has_PRIVILEGIOS` (
  `id_rol` INT NOT NULL,
  `id_privilegio` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_privilegio`),
  INDEX `fk_GRUPOS_ROLES_has_PRIVILEGIOS_PRIVILEGIOS1_idx` (`id_privilegio` ASC),
  INDEX `fk_GRUPOS_ROLES_has_PRIVILEGIOS_GRUPOS_ROLES1_idx` (`id_rol` ASC),
  CONSTRAINT `fk_GRUPOS_ROLES_has_PRIVILEGIOS_GRUPOS_ROLES1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `farmacia`.`GRUPOS_ROLES` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GRUPOS_ROLES_has_PRIVILEGIOS_PRIVILEGIOS1`
    FOREIGN KEY (`id_privilegio`)
    REFERENCES `farmacia`.`PRIVILEGIOS` (`id_privilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
